### ISSUE TITLE
Missing lodash dependency

### ISSUE THREAD

**Issue by DragonI** [Agontuk/vue-cropperjs#2]
lodash is missing from v1.02 and v2.02 packages

**Comment by Agontuk** [comment]
lodash is installed as a dependency of vue js, so I didn't include it. Are you facing any errors ?

**Comment by DragonI** [comment]
I'm using Vue 1.0.28 and webpack. lodash was not a Vue dependency. The error was lodash/omit file was not found - [line 2](https://github.com/Agontuk/vue-cropperjs/blob/1.0.2/VueCropper.js#L2)
`var omit = require('lodash/omit');`

Just checked Vue 2.0.3 and it is does have lodash as a dependency. Who knew ;)

thx for creating the wrapper

**Comment by Agontuk** [comment]
ok, I'll make a fix for the Vue 1.0 as soon as possible. Thanks for the report.

**Comment by Agontuk** [comment]
Added the lodash dependency, should work now.

**Comment by guilhermelimak** [comment]
I think this is still wrong, when I try to run it I get the error about 'lodash/omit' dependency not found but it's installed, the problem is the package name is actually 'lodash.omit' and you are requiring it as 'lodash/omit'.

**Comment by Agontuk** [comment]
You're right, I was using omit from the main lodash package. I'll update it once I'm home, thanks for noticing this.
